# Path to pre-trained weight. Download from:
# https://drive.google.com/open?id=16TjqFCJ5vT10dYPw6tpIFwsdQMZzMRbK
# weight_file: '/globalwork/jia/drow_output/PSG_small_width_depth_56/ckpts/ckpt_e40.pth'
weight_file: '/xavier_ssd/single_ckpt_e40.pth'
conf_thresh: 0.3
