# Path to pre-trained weight. Download from:
# https://drive.google.com/open?id=16TjqFCJ5vT10dYPw6tpIFwsdQMZzMRbK
# weight_file: '/home/jia/git_lidar/3d_obj_det/drow-v2/v3/output/fixed_cutout/ckpts/ckpt_e50.pth'
weight_file: '/fastwork/jia/dumps/DROW/final-WNet3xLF2p-T5-odom=False-center=each-50ep.pth.tar'
conf_thresh: 0.5
