# Path to pre-trained weight. Download from:
# https://drive.google.com/open?id=1_GQHN45QCj5pat44qbtfX-4lCOVyY97d
weight_file: '/globalwork/jia/drow_output/PSG_small_width_depth_56/ckpts/ckpt_e40.pth'
conf_thresh: 0.3
