publisher:
    visual_marker:
        topic: /lidar_visualization_marker_rear
        queue_size: 1
        latch: false

    detections:
        topic: /drow_detected_persons_rear
        queue_size: 1
        latch: false

subscriber:
    scan:
        topic: /rear_lidar/scan
        queue_size: 1
