publisher:
    visual_marker:
        topic: /lidar_visualization_marker
        queue_size: 1
        latch: false

    detections:
        topic: /drow_detected_persons
        queue_size: 1
        latch: false

subscriber:
    scan:
        topic: /front_lidar/scan
        queue_size: 1
