set(_CATKIN_CURRENT_PACKAGE "rwth_pedestrian_tracking")
set(rwth_pedestrian_tracking_VERSION "0.0.0")
set(rwth_pedestrian_tracking_MAINTAINER "Christian Dondrup <cdondrup@lincoln.ac.uk>")
set(rwth_pedestrian_tracking_PACKAGE_FORMAT "1")
set(rwth_pedestrian_tracking_BUILD_DEPENDS "cmake_modules" "message_filters" "cv_bridge" "roscpp" "sensor_msgs" "std_msgs" "rwth_perception_people_msgs" "frame_msgs" "libqt4-dev" "image_transport" "eigen")
set(rwth_pedestrian_tracking_BUILD_EXPORT_DEPENDS "message_filters" "cv_bridge" "roscpp" "sensor_msgs" "std_msgs" "rwth_perception_people_msgs" "frame_msgs" "libqt4-dev" "image_transport" "eigen")
set(rwth_pedestrian_tracking_BUILDTOOL_DEPENDS "catkin")
set(rwth_pedestrian_tracking_BUILDTOOL_EXPORT_DEPENDS )
set(rwth_pedestrian_tracking_EXEC_DEPENDS "message_filters" "cv_bridge" "roscpp" "sensor_msgs" "std_msgs" "rwth_perception_people_msgs" "frame_msgs" "libqt4-dev" "image_transport" "eigen")
set(rwth_pedestrian_tracking_RUN_DEPENDS "message_filters" "cv_bridge" "roscpp" "sensor_msgs" "std_msgs" "rwth_perception_people_msgs" "frame_msgs" "libqt4-dev" "image_transport" "eigen")
set(rwth_pedestrian_tracking_TEST_DEPENDS )
set(rwth_pedestrian_tracking_DOC_DEPENDS )
set(rwth_pedestrian_tracking_URL_WEBSITE "http://www.vision.rwth-aachen.de/")
set(rwth_pedestrian_tracking_URL_BUGTRACKER "")
set(rwth_pedestrian_tracking_URL_REPOSITORY "")
set(rwth_pedestrian_tracking_DEPRECATED "")