publisher:
    detections:
        topic: /detected_persons_synchronized
        queue_size: 1
        latch: false

    detection_votes_image:
        topic: /detection_votes_image
        queue_size: 1
        latch: false

subscriber:
    detections_yolo:
        topic: /detected_persons/yolo
        queue_size: 1

    detections_drow:
        topic: /drow_detected_persons
        queue_size: 1

    detections_drow_rear:
        topic: /drow_detected_persons_rear
        queue_size: 1
