epochs: 40
batch_size: 8
grad_norm_clip: -1.0
num_workers: 8
num_scans: 1
use_data_augumentation: False
train_with_val: False
use_polar_grid: False
focal_loss_gamma: 0.0
pedestrian_only: True

# Network type: "fc1d", "fc2d", "fc1d_fea", "fc2d_fea", "cutout" or "cutout_gating"
network: "cutout"

cutout_kwargs:
    fixed: False
    centered: True
    window_width: 1.0
    window_depth: 0.5
    num_cutout_pts: 56
    padding_val: 29.99

polar_grid_kwargs:
    min_range: 0.0
    max_range: 30.0
    range_bin_size: 0.1
    tsdf_clip: 1.0
    normalize: True

# from hyperopt
vote_kwargs:
    bin_size: 0.11691041834028301
    blur_sigma: 0.7801193226779289
    min_thresh: 0.0013299798109178708
    vote_collect_radius: 0.1560556348793659